config/routes.rb
Rails.application.routes.draw do
	get "authorize" => "session#new"
	get "callback" => "session#callback"

	get "login" => "session#index"
	get "sign_up" => "session#index"
	match "logout" => "session#destroy", via: [:get, :post, :delete]
	post 'users' => "users#create", :as => :user

	namespace :control_center do
		resources :languages, :user_roles
		resources :users do
			collection do
				get :check_user
				get :login
			end
		end
	end

	namespace :game_config do
		root :to => "dashboard#index"
	end
end

app/controllers/control_center/languages_controller.rb
module ControlCenter
	class LanguagesController < ApplicationController
		layout 'admin'
		require_role 'languages'

		# GET /languages
		# GET /languages.xml
		def index
			@languages = Language.all

			respond_to do |format|
				format.html # index.html.erb
				format.xml  { render :xml => @languages }
			end
		end

		# GET /languages/1
		# GET /languages/1.xml
		def show
			@language = Language.find(params[:id])

			respond_to do |format|
				format.html # show.html.erb
				format.xml  { render :xml => @language }
			end
		end

		# GET /languages/new
		# GET /languages/new.xml
		def new
			@language = Language.new

			respond_to do |format|
				format.html # new.html.erb
				format.xml  { render :xml => @language }
			end
		end

		# GET /languages/1/edit
		def edit
			@language = Language.find(params[:id])
		end

		# POST /languages
		# POST /languages.xml
		def create
			@language = Language.new(params[:language])

			respond_to do |format|
				if @language.save
					flash[:notice] = 'Language was successfully created.'
					format.html { redirect_to(@language) }
					format.xml  { render :xml => @language, :status => :created, :location => @language }
				else
					format.html { render :action => "new" }
					format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
				end
			end
		end

		# PUT /languages/1
		# PUT /languages/1.xml
		def update
			@language = Language.find(params[:id])

			respond_to do |format|
				if @language.update_attributes(params[:language])
					flash[:notice] = 'Language was successfully updated.'
					format.html { redirect_to(@language) }
					format.xml  { head :ok }
				else
					format.html { render :action => "edit" }
					format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
				end
			end
		end

		# DELETE /languages/1
		# DELETE /languages/1.xml
		def destroy
			@language = Language.find(params[:id])
			@language.destroy

			respond_to do |format|
				format.html { redirect_to(languages_url) }
				format.xml  { head :ok }
			end
		end
	end
end

app/controllers/control_center/user_roles_controller.rb
module ControlCenter
	class UserRolesController < ApplicationController
		layout 'admin'
		require_role 'user_roles'

		# GET /user_roles
		# GET /user_roles.xml
		def index
			@user_roles = UserRole.all

			respond_to do |format|
				format.html # index.html.erb
				format.xml  { render :xml => @user_roles }
			end
		end

		# GET /user_roles/1
		# GET /user_roles/1.xml
		def show
			@user_role = UserRole.find(params[:id])

			respond_to do |format|
				format.html # show.html.erb
				format.xml  { render :xml => @user_role }
			end
		end

		# GET /user_roles/new
		# GET /user_roles/new.xml
		def new
			@user_role = UserRole.new

			respond_to do |format|
				format.html # new.html.erb
				format.xml  { render :xml => @user_role }
			end
		end

		# GET /user_roles/1/edit
		def edit
			@user_role = UserRole.find(params[:id])
		end

		# POST /user_roles
		# POST /user_roles.xml
		def create
			@user_role = UserRole.new(params[:user_role])

			respond_to do |format|
				if @user_role.save
					format.html { redirect_to(admin_user_role_path(@user_role), :notice => 'User role was successfully created.') }
					format.xml  { render :xml => @user_role, :status => :created, :location => @user_role }
				else
					format.html { render :action => "new" }
					format.xml  { render :xml => @user_role.errors, :status => :unprocessable_entity }
				end
			end
		end

		# PUT /user_roles/1
		# PUT /user_roles/1.xml
		def update
			@user_role = UserRole.find(params[:id])

			respond_to do |format|
				if @user_role.update_attributes(params[:user_role])
					format.html { redirect_to(admin_user_role_path(@user_role), :notice => 'User role was successfully updated.') }
					format.xml  { head :ok }
				else
					format.html { render :action => "edit" }
					format.xml  { render :xml => @user_role.errors, :status => :unprocessable_entity }
				end
			end
		end

		# DELETE /user_roles/1
		# DELETE /user_roles/1.xml
		def destroy
			@user_role = UserRole.find(params[:id])
			@user_role.destroy

			respond_to do |format|
				format.html { redirect_to(admin_user_roles_url) }
				format.xml  { head :ok }
			end
		end
	end
end

app/controllers/control_center/users_controller.rb
module ControlCenter
	class UsersController < ApplicationController
		layout 'admin'
		require_role 'users'

		# GET /users
		# GET /users.xml
		def index
			@users = User.all

			respond_to do |format|
				format.html # index.html.erb
				format.xml  { render :xml => @users }
			end
		end

		# GET /users/1
		# GET /users/1.xml
		def show
			@user = User.find(params[:id])

			respond_to do |format|
				format.html # show.html.erb
				format.xml  { render :xml => @user }
			end
		end

		# GET /users/new
		# GET /users/new.xml
		def new
			@user = User.new

			respond_to do |format|
				format.html # new.html.erb
				format.xml  { render :xml => @user }
			end
		end

		# GET /users/1/edit
		def edit
			@user = User.find(params[:id])
		end

		def login
			@user = User.find(params[:id])
			return redirect_to control_center_path if @user.nil? or not has_permission('change_user')

			session[:user_id] = @user.id
			redirect_to game_path
		end

		def check_user
			@user = User.find(params[:id])
			flash[:notice] = check_user_data(@user)

			redirect_to :action => :index
		end

		# POST /users
		# POST /users.xml
		def create
			@user = User.new(params[:user])

			respond_to do |format|
				if @user.save
					format.html { redirect_to(@user, :notice => 'User was successfully created.') }
					format.xml  { render :xml => @user, :status => :created, :location => @user }
				else
					format.html { render :action => "new" }
					format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
				end
			end
		end

		# PUT /users/1
		# PUT /users/1.xml
		def update
			@user = User.find(params[:id])

			respond_to do |format|
				if @user.update_attributes(params[:user])
					format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
					format.xml  { head :ok }
				else
					format.html { render :action => "edit" }
					format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
				end
			end
		end

		# DELETE /users/1
		# DELETE /users/1.xml
		def destroy
			@user = User.find(params[:id])
			@user.destroy

			respond_to do |format|
				format.html { redirect_to(users_url) }
				format.xml  { head :ok }
			end
		end
	end
end

app/views/control_center/users/_form.html.erb
<%= simple_form_for([:control_center, @user], :html => {:multipart => true}) do |f| %>
	<%= f.input :ogi_uid %>
	<%= f.input :char_id %>
	<%= f.input :name %>
	<%= f.input :email %>
	<%= f.input :language %>
	<%= f.input :birthday %>
	<%= f.input :gender %>
	<%= f.input :premium_time %>
	<%= f.input :user_status %>
	<%= f.input :alliance_id %>
	<%= f.input :ref_id %>
	<%= f.button :submit %>
<% end %>

app/views/control_center/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/control_center/users/index.html.erb
<h1>Listing users</h1>

<table>
	<tr>
		<th>Ogi uid</th>
		<th>Char</th>
		<th>Name</th>
		<th>Email</th>
		<th>Language</th>
		<th>Birthday</th>
		<th>Gender</th>
		<th>Premium tmie</th>
		<th>User status</th>
		<th>Guild</th>
		<th>Ref</th>
		<th>Login count</th>
		<th>Failed login count</th>
		<th>Last request at</th>
		<th>Current login at</th>
		<th>Last login at</th>
		<th>Current login ip</th>
		<th>Last login ip</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @users.each do |user| %>
		<tr>
			<td><%= user.ogi_uid %></td>
			<td><%= user.char_id %></td>
			<td><%= user.name %></td>
			<td><%= user.email %></td>
			<td><%= user.language %></td>
			<td><%= user.birthday %></td>
			<td><%= user.gender %></td>
			<td><%= user.premium_time %></td>
			<td><%= user.user_status %></td>
			<td><%= user.alliance_id %></td>
			<td><%= user.ref_id %></td>
			<td><%= user.login_count %></td>
			<td><%= user.failed_login_count %></td>
			<td><%= user.last_request_at %></td>
			<td><%= user.current_login_at %></td>
			<td><%= user.last_login_at %></td>
			<td><%= user.current_login_ip %></td>
			<td><%= user.last_login_ip %></td>
			<td><%= link_to "Login", login_control_center_users_path(:id => user.id), :target => :blank %></td>
			<td><%= link_to 'Check', check_user_control_center_users_path(:id => user.id) %></td>
			<td><%= link_to 'Show', control_center_user_path(:id => user.id) %></td>
			<td><%= link_to 'Edit', edit_control_center_user_path(:id => user.id) %></td>
			<td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
	<% end %>
</table>

app/views/control_center/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ogi uid:</b>
  <%= @user.ogi_uid %>
</p>

<p>
  <b>Char:</b>
  <%= @user.char_id %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Language:</b>
  <%= @user.language %>
</p>

<p>
  <b>Birthday:</b>
  <%= @user.birthday %>
</p>

<p>
  <b>Gender:</b>
  <%= @user.gender %>
</p>

<p>
  <b>Premium tmie:</b>
  <%= @user.premium_time %>
</p>

<p>
  <b>User status:</b>
  <%= @user.user_status %>
</p>

<p>
  <b>Guild:</b>
  <%= @user.alliance_id %>
</p>

<p>
  <b>Ref:</b>
  <%= @user.ref_id %>
</p>

<p>
  <b>Login count:</b>
  <%= @user.login_count %>
</p>

<p>
  <b>Failed login count:</b>
  <%= @user.failed_login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%= @user.last_request_at %>
</p>

<p>
  <b>Current login at:</b>
  <%= @user.current_login_at %>
</p>

<p>
  <b>Last login at:</b>
  <%= @user.last_login_at %>
</p>

<p>
  <b>Current login ip:</b>
  <%= @user.current_login_ip %>
</p>

<p>
  <b>Last login ip:</b>
  <%= @user.last_login_ip %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>