config/routes.rb
Rails.application.routes.draw do
	get "authorize" => "session#new"
	get "callback" => "session#callback"

	get "login" => "session#index"
	get "sign_up" => "session#index"
	match "logout" => "session#destroy", via: [:get, :post, :delete]
	post 'users' => "users#create", :as => :user

	namespace :control_center do
		resources :languages, :user_roles
		resources :users do
			collection do
				get :check_user
				get :login
			end
		end
	end

	namespace :game_config do
		root :to => "dashboard#index"
	end
end

app/models/language.rb
class Language
	include Mongoid::Document
	#cache

	field :name, :type => String
	field :active, :type => Boolean, :default => false

	index({name: 1}, {unique: true})
end

app/controllers/control_center/languages_controller.rb
module ControlCenter
	class LanguagesController < ApplicationController
		layout 'admin'
		require_role 'languages'

		# GET /languages
		# GET /languages.xml
		def index
			@languages = Language.all

			respond_to do |format|
				format.html # index.html.erb
				format.xml  { render :xml => @languages }
			end
		end

		# GET /languages/1
		# GET /languages/1.xml
		def show
			@language = Language.find(params[:id])

			respond_to do |format|
				format.html # show.html.erb
				format.xml  { render :xml => @language }
			end
		end

		# GET /languages/new
		# GET /languages/new.xml
		def new
			@language = Language.new

			respond_to do |format|
				format.html # new.html.erb
				format.xml  { render :xml => @language }
			end
		end

		# GET /languages/1/edit
		def edit
			@language = Language.find(params[:id])
		end

		# POST /languages
		# POST /languages.xml
		def create
			@language = Language.new(params[:language])

			respond_to do |format|
				if @language.save
					flash[:notice] = 'Language was successfully created.'
					format.html { redirect_to(@language) }
					format.xml  { render :xml => @language, :status => :created, :location => @language }
				else
					format.html { render :action => "new" }
					format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
				end
			end
		end

		# PUT /languages/1
		# PUT /languages/1.xml
		def update
			@language = Language.find(params[:id])

			respond_to do |format|
				if @language.update_attributes(params[:language])
					flash[:notice] = 'Language was successfully updated.'
					format.html { redirect_to(@language) }
					format.xml  { head :ok }
				else
					format.html { render :action => "edit" }
					format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
				end
			end
		end

		# DELETE /languages/1
		# DELETE /languages/1.xml
		def destroy
			@language = Language.find(params[:id])
			@language.destroy

			respond_to do |format|
				format.html { redirect_to(languages_url) }
				format.xml  { head :ok }
			end
		end
	end
end

app/controllers/control_center/user_roles_controller.rb
module ControlCenter
	class UserRolesController < ApplicationController
		layout 'admin'
		require_role 'user_roles'

		# GET /user_roles
		# GET /user_roles.xml
		def index
			@user_roles = UserRole.all

			respond_to do |format|
				format.html # index.html.erb
				format.xml  { render :xml => @user_roles }
			end
		end

		# GET /user_roles/1
		# GET /user_roles/1.xml
		def show
			@user_role = UserRole.find(params[:id])

			respond_to do |format|
				format.html # show.html.erb
				format.xml  { render :xml => @user_role }
			end
		end

		# GET /user_roles/new
		# GET /user_roles/new.xml
		def new
			@user_role = UserRole.new

			respond_to do |format|
				format.html # new.html.erb
				format.xml  { render :xml => @user_role }
			end
		end

		# GET /user_roles/1/edit
		def edit
			@user_role = UserRole.find(params[:id])
		end

		# POST /user_roles
		# POST /user_roles.xml
		def create
			@user_role = UserRole.new(params[:user_role])

			respond_to do |format|
				if @user_role.save
					format.html { redirect_to(admin_user_role_path(@user_role), :notice => 'User role was successfully created.') }
					format.xml  { render :xml => @user_role, :status => :created, :location => @user_role }
				else
					format.html { render :action => "new" }
					format.xml  { render :xml => @user_role.errors, :status => :unprocessable_entity }
				end
			end
		end

		# PUT /user_roles/1
		# PUT /user_roles/1.xml
		def update
			@user_role = UserRole.find(params[:id])

			respond_to do |format|
				if @user_role.update_attributes(params[:user_role])
					format.html { redirect_to(admin_user_role_path(@user_role), :notice => 'User role was successfully updated.') }
					format.xml  { head :ok }
				else
					format.html { render :action => "edit" }
					format.xml  { render :xml => @user_role.errors, :status => :unprocessable_entity }
				end
			end
		end

		# DELETE /user_roles/1
		# DELETE /user_roles/1.xml
		def destroy
			@user_role = UserRole.find(params[:id])
			@user_role.destroy

			respond_to do |format|
				format.html { redirect_to(admin_user_roles_url) }
				format.xml  { head :ok }
			end
		end
	end
end

app/controllers/control_center/users_controller.rb
module ControlCenter
	class UsersController < ApplicationController
		layout 'admin'
		require_role 'users'

		# GET /users
		# GET /users.xml
		def index
			@users = User.all

			respond_to do |format|
				format.html # index.html.erb
				format.xml  { render :xml => @users }
			end
		end

		# GET /users/1
		# GET /users/1.xml
		def show
			@user = User.find(params[:id])

			respond_to do |format|
				format.html # show.html.erb
				format.xml  { render :xml => @user }
			end
		end

		# GET /users/new
		# GET /users/new.xml
		def new
			@user = User.new

			respond_to do |format|
				format.html # new.html.erb
				format.xml  { render :xml => @user }
			end
		end

		# GET /users/1/edit
		def edit
			@user = User.find(params[:id])
		end

		def login
			@user = User.find(params[:id])
			return redirect_to control_center_path if @user.nil? or not has_permission('change_user')

			session[:user_id] = @user.id
			redirect_to game_path
		end

		def check_user
			@user = User.find(params[:id])
			flash[:notice] = check_user_data(@user)

			redirect_to :action => :index
		end

		# POST /users
		# POST /users.xml
		def create
			@user = User.new(params[:user])

			respond_to do |format|
				if @user.save
					format.html { redirect_to(@user, :notice => 'User was successfully created.') }
					format.xml  { render :xml => @user, :status => :created, :location => @user }
				else
					format.html { render :action => "new" }
					format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
				end
			end
		end

		# PUT /users/1
		# PUT /users/1.xml
		def update
			@user = User.find(params[:id])

			respond_to do |format|
				if @user.update_attributes(params[:user])
					format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
					format.xml  { head :ok }
				else
					format.html { render :action => "edit" }
					format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
				end
			end
		end

		# DELETE /users/1
		# DELETE /users/1.xml
		def destroy
			@user = User.find(params[:id])
			@user.destroy

			respond_to do |format|
				format.html { redirect_to(users_url) }
				format.xml  { head :ok }
			end
		end
	end
end

app/views/control_center/languages/_form.html.erb
<%= form_tag([:control_center, @language]) do |f| %>
	<% if @language.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@language.errors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
				<% @language.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :short %><br />
		<%= f.text_field :short %>
	</p>
	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/control_center/languages/edit.html.erb
<h1>Editing language</h1>

<%= render :partial => 'admin/languages/form' %>

<%= link_to 'Show', admin_language_path(@language) %> |
<%= link_to 'Back', admin_languages_path %>

app/views/control_center/languages/index.html.erb
<h1>Listing languages</h1>

<table>
  <tr>
    <th>Short</th>
    <th>Name</th>
  </tr>

<% @languages.each do |language| %>
  <tr>
    <td><%=h language.short %></td>
    <td><%=h language.name %></td>
    <td><%= link_to 'Show', control_center_language_path(language) %></td>
    <td><%= link_to 'Edit', edit_control_center_language_path(language) %></td>
    <td><%= link_to 'Destroy', control_center_language_path(language), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New language', new_control_center_language_path %>

app/views/control_center/languages/new.html.erb
<h1>New language</h1>

<%= render :partial => 'admin/languages/form' %>

<%= link_to 'Back', admin_languages_path %>

app/views/control_center/languages/show.html.erb
<p>
	<b>Short:</b>
	<%=h @language.short %>
</p>

<p>
	<b>Name:</b>
	<%=h @language.name %>
</p>


<%= link_to 'Edit', edit_admin_language_path(@language) %> |
<%= link_to 'Back', admin_languages_path %>