config/routes.rb
Rails.application.routes.draw do
	get "authorize" => "session#new"
	get "callback" => "session#callback"

	get "login" => "session#index"
	get "sign_up" => "session#index"
	match "logout" => "session#destroy", via: [:get, :post, :delete]
	post 'users' => "users#create", :as => :user

	namespace :control_center do
		resources :languages, :user_roles
		resources :users do
			collection do
				get :check_user
				get :login
			end
		end
	end

	namespace :game_config do
		root :to => "dashboard#index"
	end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Admin</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<link href="/admin/admin.css" media="screen" rel="stylesheet" type="text/css" />
		<%= javascript_include_tag 'application' %>
		<%= csrf_meta_tag %>
	</head>

	<body>
		<div id="main">
			<div id="menu">
				<ul>
					<li><%= link_to 'Users', control_center_users_path(), {:class => (controller.controller_name == 'users')?'selected':''} %></li>
					<li><%= link_to 'User Roles', control_center_user_roles_path(), {:class => (controller.controller_name == 'user_roles')?'selected':''} %></li>
					<li><%= link_to 'Languages', control_center_languages_url(), {:class => (controller.controller_name == 'languages')?'selected':''} %></li>
					<li style="text-align: center;">------------------------------</li>
					<%= render :partial => 'layouts/admin_menu' %>
					<li><%= link_to 'Logout', logout_path %></li>
				</ul>
			</div>
			<div id="content">
				<% for name in [:notice, :warning, :message] %>
					<% if flash[name] %>
						<div id="flash_msg">
							<b><%= t("notice") %></b>
							<div id="<%= name %>">
								<div><%= flash[name] %></div>
							</div>
						</div>
					<% end %>
				<% end %>

				<%= yield %>
			</div>

			<div style="clear: both;"></div>

			<div id="footer">
				<div id="copy_r"><a href="http://www.odania-it.de" target="_blank">Copyright by Mike Petersen Odania IT</a></div>
			</div>
		</div>
	</body>
</html>

app/views/layouts/none.html.erb
<%= yield %>

app/views/layouts/simple.html.erb
<html>
	<body style="background-color: white; color: black;">
		<%= yield %>
	</body>
</html>